openapi: 3.1.1
info:
  title: Flex Gateway Manager API
  description: |-
    The Anypoint Flex Gateway Manager API provides endpoints to manage Flex Gateways registered in Anypoint Platform. It exposes all CRUD (Create, Read, Update, Delete) operations on Anypoint Managed Flex Gateways (Flex Gateways deployed to Cloudhub 2.0) through this RESTful API.
  version: 1.0.x

servers:
  - url: '{baseUri}/api/v1'
    variables:
      baseUri:
        default: https://anypoint.mulesoft.com/gatewaymanager
paths:
  /organizations/{organizationId}/usage/managed-gateways:
    get:
      operationId: Usage of Managed Gateways
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: size
          in: query
          required: false
          schema:
            type: string
            examples:
              - small
            enum:
              - small
              - large
      responses:
        '200':
          description: 'Amount of existing Managed Gateways created for the specified organization'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    resource:
                      type: string
                    value:
                      type: number
                  required:
                    - resource
                    - value
              examples:
                default:
                  value:
                    - resource: managed-gateways-small
                      value: 3
                    - resource: managed-gateways-large
                      value: 1
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/runtime-configuration:
    get:
      operationId: Get a Managed or Self-Managed Flex Gateway runtime configuration data
      description: Get the runtime configuration of a Managed or Self-Managed Flex Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: './schemas/gateway.yaml#/components/schemas/RuntimeConfigurationDetail'
          x-amf-mediaType: application/json
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
    put:
      operationId: Upsert (create or update) runtime configuration of a Managed or Self-Managed Flex Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRuntimeConfig'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: './schemas/gateway.yaml#/components/schemas/RuntimeConfigurationDetail'
          x-amf-mediaType: application/json
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways:
    get:
      operationId: List Managed Gateways
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: name
          in: query
          required: false
          schema:
            type: string
          examples:
            default:
              value: my-gateway
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
          examples:
            default:
              value: 20
        - name: sortBy
          in: query
          required: false
          schema:
            type: string
          examples:
            default:
              value: name
        - name: sortOrder
          in: query
          required: false
          schema:
            type: string
          examples:
            default:
              value: ASC
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
          examples:
            default:
              value: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayList'
              examples:
                default:
                  value:
                    content:
                      - id: d4f1a2b3-5678-9abc-def0-1234567890ab
                        name: my-gateway
                        status: RUNNING
                        size: small
                        releaseChannel: LTS
                        runtimeVersion: 1.9.3
                    totalElements: 1
                    pageNumber: 0
                    pageSize: 20
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
    post:
      operationId: Create a Managed Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGateway'
            examples:
              default:
                value:
                  name: my-new-gateway
                  targetId: f1c1b011-888e-4994-9999-e44e4a44c444
                  releaseChannel: LTS
                  runtimeVersion: 1.9.3
                  size: small
        required: false
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayDetail'
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}:
    get:
      operationId: Get Managed Gateway data
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayDetail'
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
    put:
      operationId: Update Managed Gateway data
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGateway'
            examples:
              default:
                value:
                  name: my-updated-gateway
                  targetId: f1c1b011-888e-4994-9999-e44e4a44c444
                  releaseChannel: LTS
                  runtimeVersion: 1.9.4
                  size: large
        required: false
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayDetail'
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
    delete:
      operationId: Delete a Managed Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      responses:
        '204':
          description: ''
          content: {}
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/registration:
    get:
      operationId: Get registration data for the Managed Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                  - expiration
                properties:
                  expiration:
                    type: string
                    examples:
                      - '2024-11-22T17:34:09.000Z'
              examples:
                default:
                  value:
                    expiration: '2024-11-22T17:34:09.000Z'
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/status:
    get:
      operationId: Recover current status data for the Managed Gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - ready
                  - running
                properties:
                  status:
                    type: string
                    examples:
                      - RUNNING
                  ready:
                    type: boolean
                  running:
                    type: boolean
              examples:
                running:
                  summary: A running gateway
                  value:
                    status: RUNNING
                    ready: true
                    running: true
                stopped:
                  summary: A stopped gateway
                  value:
                    status: STOPPED
                    ready: false
                    running: false
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
  /organizations/{organizationId}/environments/{environmentId}/gateways/{gatewayId}/desiredstatus:
    patch:
      operationId: Update desired status of a gateway
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: 8a2a82a0-b8c1-4457-b385-4dc1c7b8900e
        - name: environmentId
          in: path
          required: true
          schema:
            type: string
          examples:
            default:
              value: c9e28061-60f0-4e54-a048-44f053a8a993
        - name: gatewayId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          examples:
            default:
              value: d4f1a2b3-5678-9abc-def0-1234567890ab
      requestBody:
        content:
          application/json:
            schema:
              required:
                - desiredStatus
              type: object
              properties:
                desiredStatus:
                  type: string
                  examples:
                    - STARTED
                  enum:
                    - STARTED
                    - STOPPED
            examples:
              start:
                summary: Start a gateway
                value:
                  desiredStatus: STARTED
              stop:
                summary: Stop a gateway
                value:
                  desiredStatus: STOPPED
        required: false
      responses:
        '202':
          description: ''
          content:
            application/json:
              schema:
                type: object
              examples:
                default:
                  value: {}
        default:
          description: 'Response body for handled errors'
          content:
            application/json:
              schema:
                $ref: './schemas/errors.yaml#/components/schemas/GatewayManagerError'
components:
  schemas:
    GatewayList:
      required:
        - content
        - pageNumber
        - pageSize
        - totalElements
      type: object
      properties:
        content:
          type: array
          items:
            $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayOverview'
        totalElements:
          type: integer
          examples:
            - 21
        pageNumber:
          type: integer
          examples:
            - 0
        pageSize:
          type: integer
          examples:
            - 20
    CreateGateway:
      required:
        - name
        - runtimeVersion
        - releaseChannel
        - size
        - targetId
      type: object
      properties:
        name:
          type: string
          examples:
            - example-gateway
          pattern: ^(?![-0-9])([a-z0-9-]{2,41}[a-z0-9])?$
        targetId:
          type: string
          format: uuid
          examples:
            - f1c1b011-888e-4994-9999-e44e4a44c444
        releaseChannel:
          $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayReleaseChannel'
        runtimeVersion:
          type: string
          examples:
            - 1.9.3
        size:
          $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewaySize'
        configuration:
          $ref: './schemas/gateway.yaml#/components/schemas/ManagedGatewayConfiguration'
    CreateRuntimeConfig:
      type: object
      required:
        - configuration
      properties:
        configuration:
          $ref: './schemas/gateway.yaml#/components/schemas/RuntimeConfiguration'
